name: 'Dev Image CI'

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/dev-image.yml'
      - '.dockerignore'
      - '.nvmrc'
      - 'Dockerfile'
      - 'Makefile'
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/dev-image.yml'
      - '.dockerignore'
      - '.nvmrc'
      - 'Dockerfile'
      - 'Makefile'

jobs:
  dev-image-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: make build
      - run: make cirun cmd="npm ci"
      # - run: make ciall
      - run: make cirun cmd="npm run format:check"
      - run: make cirun cmd="npm run lint"
