name: 'Dev Image CI'

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/dev-image.yml'
      - '.dockerignore'
      - '.nvmrc'
      - 'Dockerfile'
      - 'Makefile'
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/dev-image.yml'
      - '.dockerignore'
      - '.nvmrc'
      - 'Dockerfile'
      - 'Makefile'

permissions:
  contents: read

jobs:
  dev-image-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - run: make build
      - run: make cirun cmd="npm ci"
      # - run: make ciall
      - run: make cirun cmd="npm run format:check"
      - run: make cirun cmd="npm run lint"
