name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          echo "See [CHANGELOG.md](https://github.com/${GITHUB_REPOSITORY}/blob/${TAG_NAME}/CHANGELOG.md) for more details." > ./release_notes.md
          RELEASE_NAME="$(jq -r '.name' ./package.json)"
          sed -i "1i${RELEASE_NAME} ${TAG_NAME}\n" ./release_notes.md
          gh release create "${TAG_NAME}" \
            --draft \
            --prerelease \
            --notes-file ./release_notes.md \
            --title "${RELEASE_NAME} ${TAG_NAME}"
