name: 'Test'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-24.04'
          - 'macos-latest'
          - 'windows-latest'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - run: npm ci

      - name: Run prettier
        if: matrix.os == 'ubuntu-24.04'
        run: npm run format:check

      - name: Run eslint
        if: matrix.os == 'ubuntu-24.04'
        run: npm run lint

      - name: Run ncc
        if: matrix.os == 'ubuntu-24.04'
        run: npm run build

      - run: npm test

      - name: Upload test coverage as artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage-${{ matrix.os }}
          path: coverage

      - uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5.5.4
