name: Test Action

on:
  push:
    branches: [main, feat/node24]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    strategy:
      matrix:
        hugo-version: ['latest', '0.160.1']
        extended: [true, false]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Hugo
        uses: ./
        with:
          hugo-version: ${{ matrix.hugo-version }}
          extended: ${{ matrix.extended }}

      - name: Verify Hugo
        run: hugo version
