name: Test Action

on:
  push:
    branches: [main, feat/node24]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hugo-version: ['latest', '0.160.1']
        extended: [true, false]
    steps:
      - uses: actions/checkout@v6

      - name: Setup Hugo
        uses: ./
        with:
          hugo-version: ${{ matrix.hugo-version }}
          extended: ${{ matrix.extended }}

      - name: Verify Hugo
        run: hugo version
