name: Update major tag

on:
  release:
    types: [released]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Update major tag
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          export TAG_NAME="${GITHUB_REF##refs/tags/}"
          export TAG_MAJOR="${TAG_NAME%%.*}"
          git tag --force -a "${TAG_MAJOR}" -m "Release ${TAG_NAME}"
          git push --force origin "${TAG_MAJOR}"
